# Generated by Django 5.0.4 on 2024-04-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_product_promotionsdiscount_support_userfeedback_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromotionsDiscount',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user_feedback',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='UserFeedback',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
