# Generated by Django 5.0.4 on 2024-04-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0005_remove_shoppingcart_date_shoppingcart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='total_price',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='total_price',
            field=models.IntegerField(blank=True),
        ),
    ]
