# Generated by Django 5.0.4 on 2024-04-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0007_method_remove_orderdetail_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Method',
        ),
    ]
