# Generated by Django 5.0.4 on 2024-04-16 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0009_orderdetail_product_orderdetail_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('offline', 'Trực Tiếp'), ('online', 'Online')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='shopping_cart',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='class.shoppingcart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_of_customer',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_of_merchant',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=2902, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
    ]
