# Generated by Django 5.0.3 on 2024-04-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0011_alter_product_price_alter_shoppingcart_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='payment',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
