# Generated by Django 5.0.6 on 2024-05-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0014_remove_product_quantity_product_date_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=True, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='quantity',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=True, max_digits=10),
        ),
    ]
